version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
before_build: nuget restore
build:     
    publish_wap: true

#######################################################################
aos: Visual Studio 2015

environment:
  matrix:
    - CLI_VERSION: 1.0.1
    - CLI_VERSION: Latest
install:
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1"
  - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Version $env:CLI_VERSION -InstallDir $env:DOTNET_INSTALL_DIR'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new
  - ps: mkdir "test\test-dotnet-new" -Force | Push-Location
  - ps: dotnet new console -lang f#
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet run a b
  - ps: Pop-Location


test: off
version: 0.0.1.{build}