version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
before_build: nuget restore
build:     
    project: DI. FortuneTeller.csproj
    project: Infestation reports.csproj
    publish_wap: true