version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
before_build: nuget restore

environment:
  matrix:
    project_name: 3. Infestation report.csproj
    project_name: 4. Dependency Injection Project.csproj

platform:
  - x86
  - Any CPU

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true